### ISSUE TITLE
工具出现list index out of range 'bool' object is not subscriptable错误

### ISSUE THREAD

**Issue by helloyw** [Jumbo-WJB/search_rbcd#1]
师傅工具出现`└─# python3 search_rbcd.py  -u test -p 'user@123' -d redteam.com -l 192.168.132.204
DC=redteam,DC=com
list index out of range
'bool' object is not subscriptable
`

**Comment by Jumbo-WJB** [comment]
解决了吗

**Comment by helloyw** [comment]
> 解决了吗

还没解决

**Comment by Jumbo-WJB** [comment]
如果不敏感的话，可以的话可以加我微信，我帮你一起看下：Jumbo_Woo
